evaluation: True

training:
  save_ckpt: true
  ckpt_dir: /home/infres/yrothlin-24/CHAL_IM05/checkpoints/resnet50_w_preprocessing
  ckpt_every: 1
  resume_from: /home/infres/yrothlin-24/CHAL_IM05/checkpoints/resnet50_w_preprocessing/best.pt
  resume: True
  monitor: macro_f1
  loss: focal
  lr: 0.001
  weight_decay: 0.01
  num_epochs: 30
  optimizer: adamw
  scheduler: cosine
  use_amp: false
  grad_clip: null
  log_step: 50
  label_smoothing: 0.0
  weights:
    - 0.131885
    - 0.167166
    - 0.287122
    - 0.512761
    - 0.738572
    - 0.786459
    - 0.760902
    - 0.792986
    - 0.716469
    - 1.409173
    - 0.335431
    - 1.824578
    - 4.536496

data:
  dataset_dir: /home/infres/yrothlin-24/CHAL_IM05/data/IMA205-challenge/test
  label_path: /home/infres/yrothlin-24/CHAL_IM05/data/IMA205-challenge/test_metadata.csv
  train_ratio: 0.8
  seed: 42
  batch_size: 64
  shuffle: true
  num_workers: 4
  pin_memory: True

model:
  num_classes: 13